export const banlist = {
    T3: 
    [
        "Academy Ruins",
        "Aetherflux Reservoir",
        "An-Zerrin Ruins",
        "Animate Dead",
        "Palinchron",
        "Great Whale",
        "Approach of the Second Sun",
        "Axis of Mortality",
        "Bolas's Citadel",
        "Nyxbloom Ancient",
        "Mana Crypt",
        "Mana Vault",
        "Hive Mind",
        "Panharmonicon",
        "Sudden Substitution",
        "Quicksilver Fountain",
        "Mana Reflection",
        "Reins of Power",
        "Ancient Tomb",
        "Emrakul, The Promised End",
        "Planar Bridge",
        "Basalt monolith",
        "Grim Monolith",
        "Memnarch",
        "Darksteel Forge",
        "Buried alive",
        "Walking Ballista",
        "Peregrine Drake",
        "Sylvan Library",
        "Smothering Tithe",
        "Cabal Coffers",
        "Captive Audience",
        "Consecrated Sphinx",
        "Craterhoof Behemoth",
        "Cyclonic Rift",
        "Dance of the Dead",
        "Deadeye Navigator",
        "Doubling Season",
        "Forbid",
        "Gaea's Cradle",
        "Karn Liberated",
        "Liliana's Contract",
        "Magus of the Tabernacle",
        "Master of Cruelties",
        "Maze of Ith",
        "Mind's Dilation",
        "Mirror Universe",
        "Mystic Remora",
        "Oath of Teferi",
        "Omniscience",
        "Pendrell Mists",
        "Phage the Untouchable",
        "Revel in Riches",
        "Revival / Revenge",
        "Rhystic Study",
        "Scapeshift",
        "Serra's Sanctum",
        "Skullclamp",
        "Test of Endurance",
        "Thousand-Year Storm",
    ],
    T2: 
    [
        "Ad Nauseam",
        "Aura Shards",
        "Avacyn, Angel of Hope",
        "Bubble Matrix",
        "Ensnaring Bridge",
        "Eye of the Storm",
        "Flash",
        "Gaddock Teeg",
        "Glacial Chasm",
        "Heartless Hidetsugu",
        "Humility",
        "Iona, Shield of Emeria",
        "Isochron Scepter",
        "Laboratory Maniac",
        "Lion's Eye Diamond",
        "Magus of the Moon",
        "Mana Drain",
        "Mindslaver",
        "Moat",
        "Necropotence",
        "Notion Thief",
        "Paradox Engine",
        "Power Artifact",
        "Pox",
        "Purphoros, God of the Forge",
        "Realm Razer",
        "Reanimate",
        "Rings of Brighthearth",
        "Rule of Law",
        "Seedborn Muse",
        "Smokestack",
        "Staff of Domination",
        "Stasis",
        "Static Orb",
        "Sun Quan, Lord of Wu",
        "The Tabernacle at Pendrell Vale",
        "Treachery",
        "Tree of Perdition",
        "Vorinclex, Voice of Hunger",
        "Winter Orb",
        "Worldgorger Dragon",
        "Yawgmoth's Will",
    ],
    T1:
    [
        "Blood Moon",
        "Boil",
        "Boiling Seas",
        "Contamination",
        "Dimensional Breach",
        "Energy Flux",
        "Tsunami",
        "Wake of Destruction",
        "Worldslayer",
        "Thassa's Oracle",
        "Flash",
 
    ],
    edited: 
    [
        "Felidar Sovereign",
        "Jace, Wielder of Mysteries",
        "Karn, the Great Creator",
        "Magister Sphinx",
        "Mana Geyser",
        "Nevermore",
        "Serra Ascendant",
        "Sorin Markov",
        "Teferi, Time Raveler"
    ]
}
