export const banlist = {
    T3: 
    [
        "Animar, Soul of Elements",
        "Baral, Chief of Compliance",
        "Brago, King Eternal",
        "Breya, Etherium Shaper",
        "Derevi, Empyrial Tactician",
        "General Tazri",
        "Ghave, Guru of Spores",
        "God-Eternal Kefnet",
        "Godo, Bandit Warlord",
        "Golos, Tireless Pilgrim",
        "Grand Arbiter Augustin IV",
        "Jace, Vryn's Prodigy",
        "Jeleva, Nephalia's Scourge",
        "Jhoira, Weatherlight Captain",
        "Kess, Dissident Mage",
        "Kraum, Ludevic's Opus",
        "Kykar, Wind's Fury",
        "Meren of Clan Nel Toth",
        "Mizzix of the Izmagnus",
        "Momir Vig, Simic Visionary",
        "Najeela, the Blade-Blossom",
        "Narset, Enlightened Master",
        "Niv-Mizzet, Parun",
        "1x Niv-Mizzet Reborn",
        "1x Oona, Queen of the Fae",
        "Prime Speaker Vannifar",
        "Prossh, Skyraider of Kher",
        "Ramos, Dragon Engine",
        "Rashmi, Eternities Crafter",
        "Scion of the Ur-Dragon",
        "Selvala, Heart of the Wilds",
        "Sidisi, Brood Tyrant",
        "Sidisi, Undead Vizier",
        "Sisay, Weatherlight Captain",
        "Taigam, Ojutai Master",
        "Tana, the Bloodsower",
        "Tasigur, the Golden Fang",
        "Teferi, Temporal Archmage",
        "The First Sliver",
        "The Gitrog Monster",
        "The Mimeoplasm",
        "Thrasios, Triton Hero",
        "Tymna the Weaver",
        "Urza, Lord High Artificer",
        "Vial Smasher the Fierce",
        "Yarok, the Desecrated",
        "Yidris, Maelstrom Wielder",
        "Yisan, the Wanderer Bard",
        "Zur the Enchanter",
        "Academy Ruins",
        "Aetherflux Reservoir",
        "An - Zerrin Ruins",
        "Approach of the Second Sun",
        "Avacyn, Angel of Hope",
        "Axis of Mortality",
        "Bolas's Citadel",
        "Cabal Coffers",
        "Captive Audience",
        "Consecrated Sphinx",
        "Craterhoof Behemoth",
        "Cyclonic Rift",
        "Deadeye Navigator",
        "Doubling Season",
        "Forbid",
        "Gaea's Cradle",
        "Karn Liberated",
        "Liliana's Contract",
        "Magus of the Tabernacle",
        "Master of Cruelties",
        "Maze of Ith",
        "Mind's Dilation",
        "Mirror Universe",
        "Oath of Teferi",
        "Omniscience",
        "Pendrell Mists",
        "Phage the Untouchable",
        "Revel in Riches",
        "Revival / Revenge",
        "Rhystic Study",
        "Scapeshift",
        "Serra's Sanctum",
        "Skullclamp",
        "Test of Endurance",
        "Thousand - Year Storm",
    ],
    T2: 
    [
        "Aura Shards",
        "Ensnaring Bridge",
        "Flash",
        "Gaddock Teeg",
        "Glacial Chasm",
        "Heartless Hidetsugu",
        "Humility",
        "Iona, Shield of Emeria",
        "Isochron Scepter",
        "Laboratory Maniac",
        "Lion's Eye Diamond",
        "Magus of the Moon",
        "Mana Drain",
        "Mindslaver",
        "Moat",
        "Notion Thief",
        "Paradox Engine",
        "Power Artifact",
        "Pox",
        "Purphoros, God of the Forge",
        "Realm Razer",
        "Rings of Brighthearth",
        "Rule of Law",
        "Seedborn Muse",
        "Smokestack",
        "Staff of Domination",
        "Stasis",
        "Static Orb",
        "The Tabernacle at Pendrell Vale",
        "Tree of Perdition",
        "Vorinclex, Voice of Hunger",
        "Winter Orb",
        "Worldgorger Dragon",
        "Yawgmoth's Will",
    ],
    T1:
    [
        "Blood Moon",
        "Boil",
        "Boiling Seas",
        "Contamination",
        "Dimensional Breach",
        "Energy Flux",
        "Tsunami",
        "Wake of Destruction",
        "Worldslayer",
    ],
    edited: 
    [
        "Felidar Sovereign",
        "Jace, Wielder of Mysteries",
        "Karn, the Great Creator",
        "Magister Sphinx",
        "Mana Geyser",
        "Nevermore",
        "Serra Ascendant",
        "Sorin Markov",
        "Teferi, Time Raveler"
    ]
}
